language: java

jdk:
  - oraclejdk8

sudo: false

install: mvn -DskipTests=true -Dbasepom.check.skip-all=true -Dmaven.javadoc.skip=true -B install
script: mvn -B verify

cache:
  directories:
  - $HOME/.m2
